# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of the HPC team of GRICAD
email: gricad-contact@univ-grenoble-alpes.fr
description: > # this means to ignore newlines until "baseurl:"
  Sharing technical stuff about system and network administration of High Performance Computing facilities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gricad-calcul.github.io/" # the base hostname & protocol for your site
github_username:  gricad

# Build settings
markdown: kramdown

theme: jekyll-theme-modernist

exclude: [ old, nix, tuto_nix, scripts ]
