# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of the HPC team of GRICAD
email: gricad-contact@univ-grenoble-alpes.fr
description: > # this means to ignore newlines until "baseurl:"
  The "pole calcul" (HPC team) of GRICAD maintains High Performance Computing
  clusters for the University of Grenoble. This blog is to share some of
  our technical stuff about Unix administration in our particular context.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gricad-calcul.github.io/" # the base hostname & protocol for your site
github_username:  gricad

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine