* Notes pour la création d'un tuto nix aux JDEV

** Format :
3h, le mardi matin, une intro suivi du tuto. Tuto en anglais.

** Public visé et objectifs?
deux cas : 
- utilisateurs 'de base' : faire qu'ils repartent avec une installe de nix fonctionnelle ET la conviction que c'est utile
  en gros : utiliser nix pour accèder à un environnement de developpement pour faire tourner ses calculs
- "developpeur" de paquet nix : créer un paquet nix pour son propre logiciel
- administrateurs cluster : montrer comment mettre en place nix sur un cluster de calcul

** Déroulement de la séance

*** Trouver un fil rouge pour illustrer le pb: un petit pgm avec de la fft et/ou du boost? ==> Franck
**** quel est le problème?
**** comment le résoudre (targz, nix et autres outils équivalents)
**** pourquoi nix est une bonne solution

*** Intro générale : Bruno reprend ses slides et on fait le point plus tard
slides : https://ciment.ujf-grenoble.fr/wiki-pub/images/f/f7/NIX_BUX_2016.pdf
2 - 3 mots sur nixos? 

But : expliquer à quoi sert nix.

*** Tuto part 1 : pour les utilisateurs 
**** installation sur leur machine ==> Fred
**** utilisation standard : les profils, installation/desinst d'un package ==> Fred
**** cas tordus (R, python, OpenCL, GPU driver …)
*** Tuto part 2 : utilisation avancé : création d'un paquet nix
trouver un exemple d'un code venant de github avec dépendances, headers ...?
==> Fançoise & Philippe
*** Tuto part 3 : installation sur un serveur de calcul (nix channel, dépôt github etc .)


* Le poster?
** voir version Philippe
** trouver exemple 'passage à l'échelle du mésocentre au centre national'


* Aide mémoire markdown:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
